// Import these definitions into a separately secured Sanity Studio.
// Publication signatures are generated by the controlled publisher, never by editors.
const str = (name: string, title: string) => ({ name, title, type: "string" });
const paragraphList = {
  name: "paragraphs",
  type: "array",
  of: [{ type: "text" }],
};
const sections = { name: "sections", type: "array", of: [{ type: "section" }] };
const publication = [
  {
    name: "publicationStatus",
    type: "string",
    options: {
      list: ["draft", "review", "approved", "published", "withdrawn"],
    },
    initialValue: "draft",
  },
  { name: "approvedAt", type: "datetime", readOnly: true },
  { name: "expiresAt", type: "datetime" },
  { name: "signature", type: "string", readOnly: true, hidden: true },
];
const mediaFields = [
  {
    name: "image",
    type: "string",
    description:
      "Use a reviewed local media filename until an approved CMS asset pipeline is configured.",
  },
  str("imageAlt", "Image alternative text"),
];
export const schemaTypes = [
  {
    name: "section",
    type: "object",
    fields: [
      str("id", "Section anchor"),
      str("title", "Heading"),
      paragraphList,
      { name: "bullets", type: "array", of: [{ type: "string" }] },
      {
        name: "table",
        type: "object",
        fields: [
          str("caption", "Table caption"),
          { name: "headings", type: "array", of: [{ type: "string" }] },
          {
            name: "rows",
            type: "array",
            of: [
              {
                type: "object",
                name: "tableRow",
                fields: [
                  { name: "cells", type: "array", of: [{ type: "string" }] },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "service",
    type: "document",
    fields: [
      ...publication,
      {
        name: "content",
        type: "object",
        fields: [
          str("slug", "Stable service slug"),
          str("name", "Service name"),
          str("headline", "Headline"),
          { name: "summary", type: "text" },
          str("cta", "Enquiry action"),
          ...mediaFields,
          str("variant", "Composition variant"),
          sections,
          {
            name: "faqs",
            type: "array",
            of: [
              {
                type: "object",
                fields: [
                  str("question", "Question"),
                  { name: "answer", type: "text" },
                ],
              },
            ],
          },
          { name: "related", type: "array", of: [{ type: "string" }] },
        ],
      },
    ],
  },
  {
    name: "insight",
    type: "document",
    fields: [
      ...publication,
      {
        name: "content",
        type: "object",
        fields: [
          str("slug", "Stable article slug"),
          str("topic", "Topic"),
          str("title", "Title"),
          { name: "summary", type: "text" },
          { name: "readMinutes", type: "number" },
          sections,
          str("related", "Related internal route"),
        ],
      },
    ],
  },
  {
    name: "editorialPage",
    type: "document",
    fields: [
      ...publication,
      {
        name: "content",
        type: "object",
        fields: [
          str("path", "Approved route"),
          str("label", "Navigation label"),
          str("title", "Headline"),
          { name: "summary", type: "text" },
          str("cta", "Enquiry action"),
          str("interest", "Enquiry interest"),
          ...mediaFields,
          str("alt", "Image alternative text"),
          sections,
        ],
      },
    ],
  },
  {
    name: "capabilityFamily",
    type: "document",
    fields: [
      str("title", "Title"),
      { name: "summary", type: "text" },
      {
        name: "services",
        type: "array",
        of: [{ type: "reference", to: [{ type: "service" }] }],
      },
    ],
  },
  {
    name: "expertiseContext",
    type: "document",
    fields: [
      str("title", "Title"),
      { name: "summary", type: "text" },
      sections,
    ],
  },
  {
    name: "navigation",
    type: "document",
    fields: [
      str("title", "Title"),
      {
        name: "links",
        type: "array",
        of: [
          {
            type: "object",
            fields: [
              str("label", "Label"),
              str("path", "Allowlisted internal path"),
            ],
          },
        ],
      },
    ],
  },
  {
    name: "approvedEvidence",
    type: "document",
    fields: [
      ...publication,
      str("wording", "Approved public wording"),
      str("context", "Public context"),
      { name: "period", type: "string" },
    ],
  },
  {
    name: "reviewedMedia",
    type: "document",
    fields: [
      str("title", "Title"),
      str("localFile", "Reviewed filename"),
      str("alt", "Alternative text"),
      str("credit", "Public credit"),
      str("licenseUrl", "License URL"),
    ],
  },
  {
    name: "siteConfiguration",
    type: "document",
    fields: [
      str("title", "Site title"),
      str("description", "Description"),
      str("atsUrl", "Verified HTTPS ATS link"),
    ],
  },
];
